[package]
name = "altered-judge-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
poise = "0.6.1"
shuttle-runtime = "0.48.0"
shuttle-serenity = "0.48.0"
tokio = "1.26.0"
tracing = "0.1.37"
serde_json = "1.0"
regex = "1.11.0"
